[package]
name = "ipc"
version.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
edition = "2024"

[dependencies]
serde.workspace = true
serde_json.workspace = true
lecoo-types.workspace = true
interprocess = "2.4"

[target.'cfg(windows)'.dependencies]
widestring = "1.0"
